In [29]:
#Every Nuron has a unique connection to every single previous nuron. Every unique input is also going to have a unique weight associate with it
#Creates a basic neuron with 3 inputs.
inputs = [1,2,3,2.5]
weights= [0.2, 0.8 , -0.5, 1.0]
bias= 2
output =inputs[0] * weights[0] + inputs[1] * weights[1] + inputs[2] * weights[2] + inputs[3] * weights[3] + bias
print(output)

4.8


In [21]:
#Every Nuron has a unique connection to every single previous nuron. Every unique input is also going to have a unique weight associate with it 
input = [1,2,3,2.5]
weights = [3.1,2.1,8.7,9.0]
bias = 3
output =input[0] * weights[0] + input[1] * weights[1] + input[2] * weights[2]  + input[3] * weights[3] + bias
print(output)

58.9


In [16]:
#Every Nuron has a unique connection to every single previous nuron. Every unique input is also going to have a unique weight associate with it 
#Creates a simple layer of neurons, with 4 inputs.
input = [1.2,5.1,2.1,5]
weights1 = [3.1,2.1,8.7,9.0]
weights2 = [2.1,4.1,6.1,5.0]
weights3 = [1.7,3.5,-6.3,-0.6]
bias1 = 3
bias2 = 4
bias3 =5
output = [input[0] * weights1[0] + input[1] * weights1[1] + input[2] * weights1[2]  + input[3] * weights1[3] + bias1,
          input[0] * weights2[0] + input[1] * weights2[1] + input[2] * weights2[2]  + input[3] * weights2[3] + bias2,
          input[0] * weights3[0] + input[1] * weights3[1] + input[2] * weights3[2]  + input[3] * weights3[3] + bias3 
         ]

print(output)

[80.7, 65.24, 8.659999999999997]


In [24]:
#Example 3 The Dot Product
import numpy as np
inputs = [1,2,3,2.5]
weights= [0.2, 0.8 , -0.5, 1.0]
bias= 2
output = np.dot(weights , inputs) + bias
print(output)


4.8


In [48]:
#Example 4 Batches, Layers, and Objects
#Doing dot product with a layer of neurons and multiple inputs
import numpy as np
inputs = [1,2,3,2.5]
weights= [[0.2, 0.8 , -0.5, 1.0],
          [0.5,-0.91,0.26,-0.5],
          [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3 , 0.5]
output = np.dot(weights , inputs) + biases
print(output)


[4.8   1.21  2.385]


In [50]:
#Example 5 Batches, Layers, and Objects
import numpy as np
inputs = [[1,2,3,2.5],
          [2.0,5.0,-1.0,2.0],
          [-1.5, 2.7, 3.3, -0.8]]
weights= [[0.2, 0.8, -0.5, 1.0],
          [0.5,-0.91,0.26,-0.5],
          [-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3 , 0.5]
output = np.dot(inputs , np.array(weights).T) + biases
print(output)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [67]:
#Example 6 Batches, Layers, and Objects
import numpy as np
np.random.seed(0)
X =[[1,2,3,2.5],
    [2.0,5.0,-1.0,2.0],
    [-1.5,2.7,3.3,-0.8]]

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs , n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

print(0.10*np.random.randn(4,3))

layer1 = Layer_Dense(4,5)
layer2 = Layer_Dense(5,2)
layer1.forward(X)
print(layer1.output)
layer2.forward(layer1.output)
print(layer2.output)


[[ 0.17640523  0.04001572  0.0978738 ]
 [ 0.22408932  0.1867558  -0.09772779]
 [ 0.09500884 -0.01513572 -0.01032189]
 [ 0.04105985  0.01440436  0.14542735]]
[[ 0.24760702  0.23532634  0.92183326 -0.87480338  0.38839981]
 [-0.07425198  0.5616412  -0.27137893 -1.03333399  0.69668176]
 [ 0.13069026 -0.30125977  0.33428499 -1.23169487 -0.06278753]]
[[ 0.0764005   0.03676484]
 [-0.07936267 -0.07683314]
 [ 0.09429592  0.05574692]]


In [5]:
#Example 7
#Relu activation
import numpy as np 
import nnfs
from nnfs.datasets import spiral_data  # See for code: https://gist.github.com/Sentdex/454cb20ec5acf0e76ee8ab8448e6266c

nnfs.init()

X, y = spiral_data(100, 3)   


class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases


class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)


layer1 = Layer_Dense(2,5)
activation1 = Activation_ReLU()

layer1.forward(X)

#print(layer1.output)
activation1.forward(layer1.output)
print(activation1.output)

[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 4.65504505e-04
  4.56846210e-05]
 [0.00000000e+00 5.93469958e-05 0.00000000e+00 2.03573116e-04
  6.10024377e-04]
 ...
 [1.13291524e-01 0.00000000e+00 0.00000000e+00 8.11079666e-02
  0.00000000e+00]
 [1.34588361e-01 0.00000000e+00 3.09493970e-02 5.66337556e-02
  0.00000000e+00]
 [1.07817926e-01 0.00000000e+00 0.00000000e+00 8.72561932e-02
  0.00000000e+00]]


In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
pip install nnfs

Note: you may need to restart the kernel to use updated packages.


In [6]:
#Softmax activation
import numpy as np 
import nnfs
from nnfs.datasets import spiral_data


nnfs.init()

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.1 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases


class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

class Activation_Softmax:
    def forward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities


X, y = spiral_data(samples=100, classes=3)

dense1 = Layer_Dense(2,3)
activation1 = Activation_ReLU()

dense2 = Layer_Dense(3, 3)
activation2 = Activation_Softmax()

dense1.forward(X)
activation1.forward(dense1.output)

dense2.forward(activation1.output)
activation2.forward(dense2.output)

print(activation2.output[:5])

[[0.33333334 0.33333334 0.33333334]
 [0.33331734 0.3333183  0.33336434]
 [0.3332888  0.33329153 0.33341965]
 [0.33325943 0.33326396 0.33347666]
 [0.33323312 0.33323926 0.33352762]]


In [8]:
#Calculating the loss with Categorical Cross Entropy
import math

softmax_output = [0.7, 0.1, 0.2]
target_output = [1, 0, 0]

loss = -(math.log(softmax_output[0]) * target_output[0] +
         math.log(softmax_output[1]) * target_output[1] +
         math.log(softmax_output[2]) * target_output[2])

print(loss)

print(-math.log(0.7))
print(-math.log(0.5))

0.35667494393873245
0.35667494393873245
0.6931471805599453


In [11]:
#Applying Categorical Cross Entropy loss to our NNFS framework
import numpy as np 
import nnfs
from nnfs.datasets import spiral_data


nnfs.init()

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases


class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

class Activation_Softmax:
    def forward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities

class Loss:
    def calculate(self, output, y):
        sample_losses = self.forward(output, y)
        data_loss = np.mean(sample_losses)
        return data_loss

class Loss_CategoricalCrossentropy(Loss):
    def forward(self, y_pred, y_true):
        samples = len(y_pred)
        y_pred_clipped = np.clip(y_pred, 1e-7, 1-1e-7)

        if len(y_true.shape) == 1:
            correct_confidences = y_pred_clipped[range(samples), y_true]

        elif len(y_true.shape) == 2:
            correct_confidences = np.sum(y_pred_clipped*y_true, axis=1)

        negative_log_likelihoods = -np.log(correct_confidences)
        return negative_log_likelihoods




X, y = spiral_data(samples=100, classes=3)

dense1 = Layer_Dense(2,3)
activation1 = Activation_ReLU()

dense2 = Layer_Dense(3, 3)
activation2 = Activation_Softmax()

dense1.forward(X)
activation1.forward(dense1.output)

dense2.forward(activation1.output)
activation2.forward(dense2.output)

print(activation2.output[:5])

loss_function = Loss_CategoricalCrossentropy()
loss = loss_function.calculate(activation2.output, y)

print("Loss:", loss)

[[0.33333334 0.33333334 0.33333334]
 [0.3333332  0.3333332  0.33333364]
 [0.3333329  0.33333293 0.3333342 ]
 [0.3333326  0.33333263 0.33333477]
 [0.33333233 0.3333324  0.33333528]]
Loss: 1.0986104
